### ISSUE TITLE
HTTP/1.1 405 Method Not Allowed

### ISSUE THREAD

**Issue by mydevice** [uber-go/atomic#67] opened 2020-03-27 08:22 UTC
node_exporter]# make
>> checking code style
>> checking license header
>> running golangci-lint
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
go: go.uber.org/atomic@v1.5.1: unrecognized import path "go.uber.org/atomic" (https fetch: Get https://go.uber.org/atomic?go-get=1: proxyconnect tcp: tls: first record does not look like a TLS handshake)
make: *** [common-lint] Error 1

node_exporter]# curl  -I https://go.uber.org
HTTP/1.0 200 Connection established

HTTP/1.1 405 Method Not Allowed
Date: Fri, 27 Mar 2020 08:22:22 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 19
Allow: GET, OPTIONS
X-Content-Type-Options: nosniff
Via: 1.1 google

**Comment by prashantv** [comment] 2020-04-01 04:27
Not able to reproduce this, are you sure this isn't an issue with your proxy?

**Comment by abhinav** [comment] 2020-05-12 21:00
Closing. Feel free to re-open if there's more information to follow-up with or if this happens again.

**Closed by abhinav** 2020-05-12 21:00 UTC
