### ISSUE TITLE
Prolbem on running make cover due to stretchr/testify/assert

### ISSUE THREAD

**Issue by asellappen** [uber-go/atomic#81] opened 2020-11-04 11:35 UTC
faced the problem while building for amd64 and ppc64le  

# go.uber.org/atomic
assert_test.go:28:2: cannot find package "github.com/stretchr/testify/assert" in any of:
	/home/travis/gopath/src/go.uber.org/atomic/vendor/github.com/stretchr/testify/assert (vendor tree)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/github.com/stretchr/testify/assert (from $GOROOT)
	/home/travis/gopath/src/github.com/stretchr/testify/assert (from $GOPATH)
FAIL	go.uber.org/atomic [setup failed]
?   	go.uber.org/atomic/internal/gen-atomicint	[no test files]
?   	go.uber.org/atomic/internal/gen-atomicwrapper	[no test files]
Makefile:61: recipe for target 'cover' failed
make: *** [cover] Error 1
The command "make cover" exited with 2.
cache.2
store build cache

and add import line as below  ,however it fails again as below can you check 

go_import_path: github.com/stretchr/testify/assert 

2.22s$ make cover
go test -coverprofile=cover.out -coverpkg  github.com/stretchr/testify/assert,github.com/stretchr/testify/assert/internal/gen-atomicint,github.com/stretchr/testify/assert/internal/gen-atomicwrapper -v ./...
# github.com/stretchr/testify/assert
import cycle not allowed in test
package github.com/stretchr/testify/assert (test)
	imports github.com/stretchr/testify/assert
FAIL	github.com/stretchr/testify/assert [setup failed]
?   	github.com/stretchr/testify/assert/internal/gen-atomicint	[no test files]
?   	github.com/stretchr/testify/assert/internal/gen-atomicwrapper	[no test files]
Makefile:61: recipe for target 'cover' failed
make: *** [cover] Error 1
The command "make cover" exited with 2.

**Comment by prashantv** [comment] 2020-11-05 03:43
Are you using a recent version of Go with Go modules support? This package uses `go mod`.

**Comment by asellappen** [comment] 2020-11-05 04:57
using go 1.15 to run and doing go_import_path: github.com/stretchr/testify/assert to invoke the module ,however i have understood the following missing from import module 

github.com/stretchr/testify/assert/internal/gen-atomicint [no test files]
github.com/stretchr/testify/assert/internal/gen-atomicwrapper [no test files]

do i need to use more than this version ?

**Comment by prashantv** [comment] 2020-11-05 16:32
The `go_import_path` is incorrect, it should be `go.uber.org/atomic`. github.com/stretchr/testify/assert is a test dependency of this module.

**Comment by asellappen** [comment] 2020-11-06 05:29
package is failing due to test dependency of  github.com/stretchr/testify/assert as below  in both cpu arch amd64 and ppc64le ,can you help to fix ?

ssert_test.go:28:2: cannot find package "github.com/stretchr/testify/assert" in any of:
	/home/travis/gopath/src/go.uber.org/atomic/vendor/github.com/stretchr/testify/assert (vendor tree)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/github.com/stretchr/testify/assert (from $GOROOT)
	/home/travis/gopath/src/github.com/stretchr/testify/assert (from $GOPATH)
FAIL	go.uber.org/atomic [setup failed]
?   	go.uber.org/atomic/internal/gen-atomicint	[no test files]
?   	go.uber.org/atomic/internal/gen-atomicwrapper	[no test files]
Makefile:61: recipe for target 'cover' failed

**Comment by prashantv** [comment] 2020-11-06 07:13
Sorry, something seems wrong with your environment, I just verified with go1.15 that everything is fine on a fresh clone,
```
$ go version
go version go1.15.4 darwin/amd64
$ go test
PASS
ok  	go.uber.org/atomic	1.451s
```

This is on amd64, darwin. Unfortunately we can't reproduce this issue, so closing this issue.

**Closed by prashantv** 2020-11-06 07:13 UTC

**Comment by asellappen** [comment] 2020-11-06 07:34
the below step at make cover is only producing issue .
go test -coverprofile=cover.out -coverpkg  go.uber.org/atomic -v ./... 


I have tried go test and it looks fine as below

ubuntu@arumugams:~/4th/atomic$ go test
go: downloading github.com/stretchr/testify v1.3.0
go: extracting github.com/stretchr/testify v1.3.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: extracting github.com/pmezard/go-difflib v1.0.0
go: extracting github.com/davecgh/go-spew v1.1.1
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/pmezard/go-difflib v1.0.0
PASS
ok      go.uber.org/atomic      0.599s
-------------------------------------------
go test is fine ,However make cover which is part of package is producing the issue as below



ubuntu@arumugams:~/4th/atomic$ make cover
go test -coverprofile=cover.out -coverpkg  go.uber.org/atomic -v ./...
=== RUN   TestBool
=== RUN   TestBool/JSON/Marshal
=== RUN   TestBool/JSON/Unmarshal
=== RUN   TestBool/JSON/Unmarshal/Error
=== RUN   TestBool/String
=== RUN   TestBool/String/true
=== RUN   TestBool/String/false
--- PASS: TestBool (0.00s)
    --- PASS: TestBool/JSON/Marshal (0.00s)
    --- PASS: TestBool/JSON/Unmarshal (0.00s)
    --- PASS: TestBool/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestBool/String (0.00s)
        --- PASS: TestBool/String/true (0.00s)
        --- PASS: TestBool/String/false (0.00s)
=== RUN   TestDuration
=== RUN   TestDuration/JSON/Marshal
=== RUN   TestDuration/JSON/Unmarshal
=== RUN   TestDuration/JSON/Unmarshal/Error
=== RUN   TestDuration/String
--- PASS: TestDuration (0.00s)
    --- PASS: TestDuration/JSON/Marshal (0.00s)
    --- PASS: TestDuration/JSON/Unmarshal (0.00s)
    --- PASS: TestDuration/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestDuration/String (0.00s)
=== RUN   TestErrorByValue
--- PASS: TestErrorByValue (0.00s)
=== RUN   TestNewErrorWithNilArgument
--- PASS: TestNewErrorWithNilArgument (0.00s)
=== RUN   TestErrorCanStoreNil
--- PASS: TestErrorCanStoreNil (0.00s)
=== RUN   TestNewErrorWithError
--- PASS: TestNewErrorWithError (0.00s)
=== RUN   TestFloat64
=== RUN   TestFloat64/JSON/Marshal
=== RUN   TestFloat64/JSON/Unmarshal
=== RUN   TestFloat64/JSON/Unmarshal/Error
=== RUN   TestFloat64/String
--- PASS: TestFloat64 (0.00s)
    --- PASS: TestFloat64/JSON/Marshal (0.00s)
    --- PASS: TestFloat64/JSON/Unmarshal (0.00s)
    --- PASS: TestFloat64/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestFloat64/String (0.00s)
=== RUN   TestInt32
=== RUN   TestInt32/JSON/Marshal
=== RUN   TestInt32/JSON/Unmarshal
=== RUN   TestInt32/JSON/Unmarshal/Error
=== RUN   TestInt32/String
=== RUN   TestInt32/String/positive
=== RUN   TestInt32/String/negative
--- PASS: TestInt32 (0.00s)
    --- PASS: TestInt32/JSON/Marshal (0.00s)
    --- PASS: TestInt32/JSON/Unmarshal (0.00s)
    --- PASS: TestInt32/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestInt32/String (0.00s)
        --- PASS: TestInt32/String/positive (0.00s)
        --- PASS: TestInt32/String/negative (0.00s)
=== RUN   TestInt64
=== RUN   TestInt64/JSON/Marshal
=== RUN   TestInt64/JSON/Unmarshal
=== RUN   TestInt64/JSON/Unmarshal/Error
=== RUN   TestInt64/String
=== RUN   TestInt64/String/positive
=== RUN   TestInt64/String/negative
--- PASS: TestInt64 (0.00s)
    --- PASS: TestInt64/JSON/Marshal (0.00s)
    --- PASS: TestInt64/JSON/Unmarshal (0.00s)
    --- PASS: TestInt64/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestInt64/String (0.00s)
        --- PASS: TestInt64/String/positive (0.00s)
        --- PASS: TestInt64/String/negative (0.00s)
=== RUN   TestNocmpComparability
=== RUN   TestNocmpComparability/nocmp_struct
=== RUN   TestNocmpComparability/struct_with_nocmp_embedded
=== RUN   TestNocmpComparability/pointer_to_struct_with_nocmp_embedded
=== RUN   TestNocmpComparability/Bool
=== RUN   TestNocmpComparability/Duration
=== RUN   TestNocmpComparability/Error
=== RUN   TestNocmpComparability/Float64
=== RUN   TestNocmpComparability/Int32
=== RUN   TestNocmpComparability/Int64
=== RUN   TestNocmpComparability/String
=== RUN   TestNocmpComparability/Uint32
=== RUN   TestNocmpComparability/Uint64
=== RUN   TestNocmpComparability/Value
--- PASS: TestNocmpComparability (0.00s)
    --- PASS: TestNocmpComparability/nocmp_struct (0.00s)
    --- PASS: TestNocmpComparability/struct_with_nocmp_embedded (0.00s)
    --- PASS: TestNocmpComparability/pointer_to_struct_with_nocmp_embedded (0.00s)
    --- PASS: TestNocmpComparability/Bool (0.00s)
    --- PASS: TestNocmpComparability/Duration (0.00s)
    --- PASS: TestNocmpComparability/Error (0.00s)
    --- PASS: TestNocmpComparability/Float64 (0.00s)
    --- PASS: TestNocmpComparability/Int32 (0.00s)
    --- PASS: TestNocmpComparability/Int64 (0.00s)
    --- PASS: TestNocmpComparability/String (0.00s)
    --- PASS: TestNocmpComparability/Uint32 (0.00s)
    --- PASS: TestNocmpComparability/Uint64 (0.00s)
    --- PASS: TestNocmpComparability/Value (0.00s)
=== RUN   TestNocmpSize
--- PASS: TestNocmpSize (0.00s)
=== RUN   TestNocmpCopy
=== RUN   TestNocmpCopy/struct_copy
=== RUN   TestNocmpCopy/pointer_copy
--- PASS: TestNocmpCopy (0.00s)
    --- PASS: TestNocmpCopy/struct_copy (0.00s)
    --- PASS: TestNocmpCopy/pointer_copy (0.00s)
=== RUN   TestNocmpIntegration
--- PASS: TestNocmpIntegration (1.09s)
=== RUN   TestStress
=== RUN   TestStress/f64
=== RUN   TestStress/bool
=== RUN   TestStress/error
=== RUN   TestStress/i64
=== RUN   TestStress/u32/std
=== RUN   TestStress/u32
=== RUN   TestStress/u64/std
=== RUN   TestStress/u64
=== RUN   TestStress/i32/std
=== RUN   TestStress/i32
=== RUN   TestStress/i64/std
=== RUN   TestStress/string
=== RUN   TestStress/duration
--- PASS: TestStress (0.02s)
    --- PASS: TestStress/f64 (0.01s)
    --- PASS: TestStress/bool (0.00s)
    --- PASS: TestStress/error (0.00s)
    --- PASS: TestStress/i64 (0.00s)
    --- PASS: TestStress/u32/std (0.00s)
    --- PASS: TestStress/u32 (0.00s)
    --- PASS: TestStress/u64/std (0.00s)
    --- PASS: TestStress/u64 (0.00s)
    --- PASS: TestStress/i32/std (0.00s)
    --- PASS: TestStress/i32 (0.00s)
    --- PASS: TestStress/i64/std (0.00s)
    --- PASS: TestStress/string (0.01s)
    --- PASS: TestStress/duration (0.00s)
=== RUN   TestStringNoInitialValue
--- PASS: TestStringNoInitialValue (0.00s)
=== RUN   TestString
=== RUN   TestString/JSON/Marshal
=== RUN   TestString/JSON/Unmarshal
=== RUN   TestString/JSON/Unmarshal/Error
=== RUN   TestString/XML/Marshal
=== RUN   TestString/XML/Unmarshal
=== RUN   TestString/String
--- PASS: TestString (0.00s)
    --- PASS: TestString/JSON/Marshal (0.00s)
    --- PASS: TestString/JSON/Unmarshal (0.00s)
    --- PASS: TestString/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestString/XML/Marshal (0.00s)
    --- PASS: TestString/XML/Unmarshal (0.00s)
    --- PASS: TestString/String (0.00s)
=== RUN   TestUint32
=== RUN   TestUint32/JSON/Marshal
=== RUN   TestUint32/JSON/Unmarshal
=== RUN   TestUint32/JSON/Unmarshal/Error
=== RUN   TestUint32/String
--- PASS: TestUint32 (0.00s)
    --- PASS: TestUint32/JSON/Marshal (0.00s)
    --- PASS: TestUint32/JSON/Unmarshal (0.00s)
    --- PASS: TestUint32/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestUint32/String (0.00s)
=== RUN   TestUint64
=== RUN   TestUint64/JSON/Marshal
=== RUN   TestUint64/JSON/Unmarshal
=== RUN   TestUint64/JSON/Unmarshal/Error
=== RUN   TestUint64/String
--- PASS: TestUint64 (0.00s)
    --- PASS: TestUint64/JSON/Marshal (0.00s)
    --- PASS: TestUint64/JSON/Unmarshal (0.00s)
    --- PASS: TestUint64/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestUint64/String (0.00s)
=== RUN   TestValue
--- PASS: TestValue (0.00s)
=== RUN   Example
--- PASS: Example (0.00s)
PASS
coverage: 100.0% of statements in go.uber.org/atomic
ok      go.uber.org/atomic      1.124s  coverage: 100.0% of statements in go.uber.org/atomic
?       go.uber.org/atomic/internal/gen-atomicint       [no test files]
?       go.uber.org/atomic/internal/gen-atomicwrapper   [no test files]
go tool cover -html=cover.out -o cover.html
ubuntu@arumugams:~/4th/atomic$

**Comment by prashantv** [comment] 2020-11-06 23:50
This still seems like an environment issue, it works fine from a clean clone:
```
> make cover
go test -coverprofile=cover.out -coverpkg  go.uber.org/atomic -v ./...
=== RUN   TestBool
=== RUN   TestBool/JSON/Marshal
=== RUN   TestBool/JSON/Unmarshal
=== RUN   TestBool/JSON/Unmarshal/Error
=== RUN   TestBool/String
=== RUN   TestBool/String/true
=== RUN   TestBool/String/false
--- PASS: TestBool (0.00s)
    --- PASS: TestBool/JSON/Marshal (0.00s)
    --- PASS: TestBool/JSON/Unmarshal (0.00s)
    --- PASS: TestBool/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestBool/String (0.00s)
        --- PASS: TestBool/String/true (0.00s)
        --- PASS: TestBool/String/false (0.00s)
=== RUN   TestDuration
=== RUN   TestDuration/JSON/Marshal
=== RUN   TestDuration/JSON/Unmarshal
=== RUN   TestDuration/JSON/Unmarshal/Error
=== RUN   TestDuration/String
--- PASS: TestDuration (0.00s)
    --- PASS: TestDuration/JSON/Marshal (0.00s)
    --- PASS: TestDuration/JSON/Unmarshal (0.00s)
    --- PASS: TestDuration/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestDuration/String (0.00s)
=== RUN   TestErrorByValue
--- PASS: TestErrorByValue (0.00s)
=== RUN   TestNewErrorWithNilArgument
--- PASS: TestNewErrorWithNilArgument (0.00s)
=== RUN   TestErrorCanStoreNil
--- PASS: TestErrorCanStoreNil (0.00s)
=== RUN   TestNewErrorWithError
--- PASS: TestNewErrorWithError (0.00s)
=== RUN   TestFloat64
=== RUN   TestFloat64/JSON/Marshal
=== RUN   TestFloat64/JSON/Unmarshal
=== RUN   TestFloat64/JSON/Unmarshal/Error
=== RUN   TestFloat64/String
--- PASS: TestFloat64 (0.00s)
    --- PASS: TestFloat64/JSON/Marshal (0.00s)
    --- PASS: TestFloat64/JSON/Unmarshal (0.00s)
    --- PASS: TestFloat64/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestFloat64/String (0.00s)
=== RUN   TestInt32
=== RUN   TestInt32/JSON/Marshal
=== RUN   TestInt32/JSON/Unmarshal
=== RUN   TestInt32/JSON/Unmarshal/Error
=== RUN   TestInt32/String
=== RUN   TestInt32/String/positive
=== RUN   TestInt32/String/negative
--- PASS: TestInt32 (0.00s)
    --- PASS: TestInt32/JSON/Marshal (0.00s)
    --- PASS: TestInt32/JSON/Unmarshal (0.00s)
    --- PASS: TestInt32/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestInt32/String (0.00s)
        --- PASS: TestInt32/String/positive (0.00s)
        --- PASS: TestInt32/String/negative (0.00s)
=== RUN   TestInt64
=== RUN   TestInt64/JSON/Marshal
=== RUN   TestInt64/JSON/Unmarshal
=== RUN   TestInt64/JSON/Unmarshal/Error
=== RUN   TestInt64/String
=== RUN   TestInt64/String/positive
=== RUN   TestInt64/String/negative
--- PASS: TestInt64 (0.00s)
    --- PASS: TestInt64/JSON/Marshal (0.00s)
    --- PASS: TestInt64/JSON/Unmarshal (0.00s)
    --- PASS: TestInt64/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestInt64/String (0.00s)
        --- PASS: TestInt64/String/positive (0.00s)
        --- PASS: TestInt64/String/negative (0.00s)
=== RUN   TestNocmpComparability
=== RUN   TestNocmpComparability/nocmp_struct
=== RUN   TestNocmpComparability/struct_with_nocmp_embedded
=== RUN   TestNocmpComparability/pointer_to_struct_with_nocmp_embedded
=== RUN   TestNocmpComparability/Bool
=== RUN   TestNocmpComparability/Duration
=== RUN   TestNocmpComparability/Error
=== RUN   TestNocmpComparability/Float64
=== RUN   TestNocmpComparability/Int32
=== RUN   TestNocmpComparability/Int64
=== RUN   TestNocmpComparability/String
=== RUN   TestNocmpComparability/Uint32
=== RUN   TestNocmpComparability/Uint64
=== RUN   TestNocmpComparability/Value
--- PASS: TestNocmpComparability (0.00s)
    --- PASS: TestNocmpComparability/nocmp_struct (0.00s)
    --- PASS: TestNocmpComparability/struct_with_nocmp_embedded (0.00s)
    --- PASS: TestNocmpComparability/pointer_to_struct_with_nocmp_embedded (0.00s)
    --- PASS: TestNocmpComparability/Bool (0.00s)
    --- PASS: TestNocmpComparability/Duration (0.00s)
    --- PASS: TestNocmpComparability/Error (0.00s)
    --- PASS: TestNocmpComparability/Float64 (0.00s)
    --- PASS: TestNocmpComparability/Int32 (0.00s)
    --- PASS: TestNocmpComparability/Int64 (0.00s)
    --- PASS: TestNocmpComparability/String (0.00s)
    --- PASS: TestNocmpComparability/Uint32 (0.00s)
    --- PASS: TestNocmpComparability/Uint64 (0.00s)
    --- PASS: TestNocmpComparability/Value (0.00s)
=== RUN   TestNocmpSize
--- PASS: TestNocmpSize (0.00s)
=== RUN   TestNocmpCopy
=== RUN   TestNocmpCopy/struct_copy
=== RUN   TestNocmpCopy/pointer_copy
--- PASS: TestNocmpCopy (0.00s)
    --- PASS: TestNocmpCopy/struct_copy (0.00s)
    --- PASS: TestNocmpCopy/pointer_copy (0.00s)
=== RUN   TestNocmpIntegration
--- PASS: TestNocmpIntegration (0.07s)
=== RUN   TestStress
=== RUN   TestStress/u64/std
=== RUN   TestStress/u64
=== RUN   TestStress/f64
=== RUN   TestStress/i64
=== RUN   TestStress/u32/std
=== RUN   TestStress/i64/std
=== RUN   TestStress/u32
=== RUN   TestStress/bool
=== RUN   TestStress/string
=== RUN   TestStress/duration
=== RUN   TestStress/error
=== RUN   TestStress/i32/std
=== RUN   TestStress/i32
--- PASS: TestStress (0.01s)
    --- PASS: TestStress/u64/std (0.00s)
    --- PASS: TestStress/u64 (0.00s)
    --- PASS: TestStress/f64 (0.00s)
    --- PASS: TestStress/i64 (0.00s)
    --- PASS: TestStress/u32/std (0.00s)
    --- PASS: TestStress/i64/std (0.00s)
    --- PASS: TestStress/u32 (0.00s)
    --- PASS: TestStress/bool (0.00s)
    --- PASS: TestStress/string (0.00s)
    --- PASS: TestStress/duration (0.00s)
    --- PASS: TestStress/error (0.00s)
    --- PASS: TestStress/i32/std (0.00s)
    --- PASS: TestStress/i32 (0.00s)
=== RUN   TestStringNoInitialValue
--- PASS: TestStringNoInitialValue (0.00s)
=== RUN   TestString
=== RUN   TestString/JSON/Marshal
=== RUN   TestString/JSON/Unmarshal
=== RUN   TestString/JSON/Unmarshal/Error
=== RUN   TestString/XML/Marshal
=== RUN   TestString/XML/Unmarshal
=== RUN   TestString/String
--- PASS: TestString (0.00s)
    --- PASS: TestString/JSON/Marshal (0.00s)
    --- PASS: TestString/JSON/Unmarshal (0.00s)
    --- PASS: TestString/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestString/XML/Marshal (0.00s)
    --- PASS: TestString/XML/Unmarshal (0.00s)
    --- PASS: TestString/String (0.00s)
=== RUN   TestUint32
=== RUN   TestUint32/JSON/Marshal
=== RUN   TestUint32/JSON/Unmarshal
=== RUN   TestUint32/JSON/Unmarshal/Error
=== RUN   TestUint32/String
--- PASS: TestUint32 (0.00s)
    --- PASS: TestUint32/JSON/Marshal (0.00s)
    --- PASS: TestUint32/JSON/Unmarshal (0.00s)
    --- PASS: TestUint32/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestUint32/String (0.00s)
=== RUN   TestUint64
=== RUN   TestUint64/JSON/Marshal
=== RUN   TestUint64/JSON/Unmarshal
=== RUN   TestUint64/JSON/Unmarshal/Error
=== RUN   TestUint64/String
--- PASS: TestUint64 (0.00s)
    --- PASS: TestUint64/JSON/Marshal (0.00s)
    --- PASS: TestUint64/JSON/Unmarshal (0.00s)
    --- PASS: TestUint64/JSON/Unmarshal/Error (0.00s)
    --- PASS: TestUint64/String (0.00s)
=== RUN   TestValue
--- PASS: TestValue (0.00s)
=== RUN   Example
--- PASS: Example (0.00s)
PASS
coverage: 100.0% of statements in go.uber.org/atomic
ok      go.uber.org/atomic      0.082s  coverage: 100.0% of statements in go.uber.org/atomic
?       go.uber.org/atomic/internal/gen-atomicint       [no test files]
?       go.uber.org/atomic/internal/gen-atomicwrapper   [no test files]
go tool cover -html=cover.out -o cover.html
```

Sorry we cannot help you any further.
